"""Daily rotating quotes."""
from datetime import date

QUOTES = [
    ("The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius"),
    ("Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius"),
    ("You have power over your mind, not outside events. Realize this, and you will find strength.", "Marcus Aurelius"),
    ("Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius"),
    ("If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius"),
    ("Begin at once to live, and count each separate day as a separate life.", "Seneca"),
    ("Luck is what happens when preparation meets opportunity.", "Seneca"),
    ("Per aspera ad astra. (Through hardship to the stars)", "Seneca"),
    ("It is not that I'm so smart, it's just that I stay with problems longer.", "Albert Einstein"),
    ("He who has a why to live can bear almost any how.", "Nietzsche"),
    ("The man who moves a mountain begins by carrying away small stones.", "Confucius"),
    ("Stop being a prisoner of your past. Become the architect of your future.", "Robin Sharma"),
    ("Small daily improvements over time lead to stunning results.", "Robin Sharma"),
    ("Victims recite problems. Leaders deliver solutions.", "Robin Sharma"),
    ("The quality of your life is determined by the quality of your thoughts.", "Robin Sharma"),
    ("World-class performers don't get lucky. They just prepare more than everyone else.", "Robin Sharma"),
    ("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
    ("Move fast and break things. Unless you are breaking stuff you are not moving fast enough.", "Mark Zuckerberg"),
    ("Make something people want.", "Paul Graham"),
    ("It's easier to ask forgiveness than it is to get permission.", "Grace Hopper"),
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("Stay hungry, stay foolish.", "Steve Jobs"),
    ("Innovation distinguishes between a leader and a follower.", "Steve Jobs"),
    ("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"),
    ("Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", "Steve Jobs"),
    ("If you're not embarrassed by the first version of your product, you've launched too late.", "Reid Hoffman"),
    ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"),
    ("The secret of getting ahead is getting started.", "Mark Twain"),
    ("Do not pray for easy lives. Pray to be stronger men.", "JFK"),
    ("Ask not what your country can do for you, ask what you can do for your country.", "JFK"),
    ("Think different.", "Apple"),
    ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    ("It always seems impossible until it's done.", "Nelson Mandela"),
    ("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    ("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
    ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
    ("The measure of intelligence is the ability to change.", "Albert Einstein"),
    ("Programs must be written for people to read, and only incidentally for machines to execute.", "Harold Abelson"),
    ("Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", "Martin Fowler"),
    ("First, solve the problem. Then, write the code.", "John Johnson"),
    ("Code is like humor. When you have to explain it, it's bad.", "Cory House"),
    ("Simplicity is the soul of efficiency.", "Austin Freeman"),
    ("The sooner you start coding, the longer the program will take.", "Roy Carlson"),
    ("If debugging is the process of removing software bugs, then programming must be the process of putting them in.", "Edsger Dijkstra"),
    ("I'm not a great programmer; I'm just a good programmer with great habits.", "Kent Beck"),
    ("Talk is cheap. Show me the code.", "Linus Torvalds"),
    ("The best performance improvement is the transition from the nonworking state to the working state.", "John Ousterhout"),
    ("The most important property of a program is whether it accomplishes the intention of its user.", "C.A.R. Hoare"),
    ("Premature optimization is the root of all evil.", "Donald Knuth"),
    ("Debugging is twice as hard as writing the code in the first place.", "Brian Kernighan"),
    ("Walking on water and developing software from a specification are easy if both are frozen.", "Edward V. Berard"),
]

def get_daily_quote():
    idx = date.today().toordinal() % len(QUOTES)
    return QUOTES[idx]
